### ISSUE TITLE
An HTML Templating system

### ISSUE THREAD

**Issue by Hackmastr** [silgy/silgy#2]
Hello,

I've been toying around with Silgy for a while now, and I like it! It's pretty fast and nice.
The only issue I've for now, is, are there any plans for HTML templating system? Or Is there some sort of library one can use with Silgy?

Cheers!

**Comment by silgy** [comment]
Hi, thanks!

You're right, there would be nice to have something to automate HTML generating. For now, I'm planning on:

1) Adding "snippets", that is snippets of text (be it HTML or whatever else), read on startup like resources, but accessible from the code, so there would be something like this:

Let `about.html` contain only a HTML div, without HTML header nor footer, and it would lie in the separate directory (it'll probably be `ins` or `snippets`), not directly accessible for a client, and in the code:

```
header(ci);
OUT_SNIPPET("about.html");
footer(ci);
```

So that would save wrapping static HTML parts in OUT macros, but allowing at the same time to keep generated header and footer.

2) I was thinking about adding markdown parser, though not as an immediate priority.

3) I have a small piece that generates typical HTML table with simple CRUD for my own projects, however wasn't thinking about adding it permanently, because that would be stepping into the whole new area and much about personal taste, but I'll publish it somehow, perhaps more as a Silgy usage example.

4) You might be interested in [RESTful API generator](https://silgy.org/restapigen) for Silgy projects.

Cheers!
Jurek

**Comment by Hackmastr** [comment]
Cheers! Sounds good!
The API sounds good, seperating HTML and back end, hmm. Great idea actually :D!

**Comment by silgy** [comment]
[OUT_SNIPPET](https://github.com/silgy/silgy/wiki/OUT_SNIPPET) is now available.

**Comment by rebootcode** [comment]
Any possible way to pass value as variable to template?

**Comment by silgy** [comment]
Not at the moment. I will explore the idea though, thanks.

**Comment by rebootcode** [comment]
How can one pass dynamic data to HTML pages? using `OUT_SNIPPET`?

Let's say, I have a list of product, pagination count, other info fetched from the database and I want to print them out in "product.html". How these data is going to get passed to it?

**Comment by silgy** [comment]
Currently, OUT_SNIPPET serves adding only fixed parts to the output buffer. To add any variables you'd need to use separate lines like this:

```
header(ci);
OUT_SNIPPET("page_part_1.html");
static Cproducts rec;

if ( rec.Get(id) )
    OUT("<div>%d %s</div>", id, rec.name);
else
    OUT("<div>Product %d not found.</div>", id);

OUT_SNIPPET("page_part_2.html");
footer(ci);
```

I'm thinking about adding double curly braces variables support in the future.

There is also silgy_render_md() available, I should add OUT_SNIPPET_MD macro soon.
